---
title: "Homework 1"
author: "Sidney Gerst"
date: "1/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load packages
library(tidyverse)
library(janitor)

```


1. Mean Density of Adults
```{r echo = F}

#read in adult data
all_org <- read_csv("adult_other.csv")

#filter for only the adult fish
adults_clean <- all_org %>%
  clean_names( case = "snake") %>%
  filter(grepl('Adult', organism)) %>%
  gather(place, Density, rarotonga_2009:aitutaki_2018)  %>%
  separate(place, c("Place", "Year"), "_")

fish_plot <- ggplot(adults_clean, 
                       aes(fill = Year, x = Place, y = Density)) +
  geom_bar(position = "dodge", stat = "identity", color = "black") +
  geom_errorbar(aes(ymin = Density, ymax = Density + ci), 
                width=.8, position=position_dodge(.9)) +
  facet_wrap(~organism, scales = "free_y") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))+
  labs(title = "Adult Density Comparison")

fish_plot



```


